### ISSUE TITLE
It doesn't work in some cases with Less

### ISSUE THREAD

**Issue by BroFox86** [robertnabbe/CommentAlign#1]
Hi. The plugin doesn't work in cases when comments follow after variables. In other, common cases it work properly. It's not a big deal for me, but it will be nice if you fix it.

An example:

Before:
![2017-05-31 0 33 10](https://cloud.githubusercontent.com/assets/23554264/26606377/6034523c-459a-11e7-891a-dd224b2ab76f.png)

After:
![2017-05-31 0 33 32](https://cloud.githubusercontent.com/assets/23554264/26606378/6066fa84-459a-11e7-88cb-ff7d53014630.png)

**Comment by robertnabbe** [comment]
Hello there,

I'm definitely aware this code can behave a little fickle at times. My guess it there were still a few trailing spaces after your variables? That is the only situation in which I've seen results similar to yours. Make sure to not add any (unnecessary) additional trailing spaces and it should behave fine:

![case1](https://cloud.githubusercontent.com/assets/13839643/26643675/b76d1b58-45f7-11e7-8fec-e630b0621395.gif)

..and with variables aligned:

![case2](https://cloud.githubusercontent.com/assets/13839643/26643683/c34120f0-45f7-11e7-9f7c-b3d8b1f8d9aa.gif)
